<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch09.Supplemental._05.Serialization</RootNamespace>
    <AssemblyName>CSharp.Ch09.Supplemental.05.Serialization</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization.Formatters" />
    <Reference Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
