<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch12.Supplemental._02.PasswordHashingDoneRight</RootNamespace>
    <AssemblyName>CSharp.Ch12.Supplemental.02.PasswordHashingDoneRight</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
