<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch12.Supplemental._01.DigitalSignaturesDeepDive</RootNamespace>
    <AssemblyName>CSharp.Ch12.Supplemental.01.DigitalSignaturesDeepDive</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
