<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch10.Supplemental._04.IQueryableVsIEnumerable</RootNamespace>
    <AssemblyName>CSharp.Ch10.Supplemental.04.IQueryableVsIEnumerable</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
