<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch09.Supplemental._02.SqlInjection</RootNamespace>
    <AssemblyName>CSharp.Ch09.Supplemental.02.SqlInjection</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
