//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     SYNTAX:  wsdl.exe /l:cs "<path to wsdl file>" /o:"<output CS class file path>"
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ExampleWebServiceSoap", Namespace="http://tempuri.org/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceResponseBase))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRequestBase))]
public partial class ExampleWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback PingOperationCompleted;
    
    private System.Threading.SendOrPostCallback TestServiceOperationCompleted;
    
    private System.Threading.SendOrPostCallback TestServiceRestOperationCompleted;
    
    private System.Threading.SendOrPostCallback LookupLocationOperationCompleted;
    
    private System.Threading.SendOrPostCallback LookupLocationRestOperationCompleted;
    
    /// <remarks/>
    public ExampleWebService() {
        this.Url = "https://localhost:44355/ExampleWebService.asmx";
    }
    
    /// <remarks/>
    public event PingCompletedEventHandler PingCompleted;
    
    /// <remarks/>
    public event TestServiceCompletedEventHandler TestServiceCompleted;
    
    /// <remarks/>
    public event TestServiceRestCompletedEventHandler TestServiceRestCompleted;
    
    /// <remarks/>
    public event LookupLocationCompletedEventHandler LookupLocationCompleted;
    
    /// <remarks/>
    public event LookupLocationRestCompletedEventHandler LookupLocationRestCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Ping() {
        object[] results = this.Invoke("Ping", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Ping", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndPing(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void PingAsync() {
        this.PingAsync(null);
    }
    
    /// <remarks/>
    public void PingAsync(object userState) {
        if ((this.PingOperationCompleted == null)) {
            this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
        }
        this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
    }
    
    private void OnPingOperationCompleted(object arg) {
        if ((this.PingCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ServiceTestResponse TestService(ServiceTestRequest request) {
        object[] results = this.Invoke("TestService", new object[] {
                    request});
        return ((ServiceTestResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTestService(ServiceTestRequest request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("TestService", new object[] {
                    request}, callback, asyncState);
    }
    
    /// <remarks/>
    public ServiceTestResponse EndTestService(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ServiceTestResponse)(results[0]));
    }
    
    /// <remarks/>
    public void TestServiceAsync(ServiceTestRequest request) {
        this.TestServiceAsync(request, null);
    }
    
    /// <remarks/>
    public void TestServiceAsync(ServiceTestRequest request, object userState) {
        if ((this.TestServiceOperationCompleted == null)) {
            this.TestServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestServiceOperationCompleted);
        }
        this.InvokeAsync("TestService", new object[] {
                    request}, this.TestServiceOperationCompleted, userState);
    }
    
    private void OnTestServiceOperationCompleted(object arg) {
        if ((this.TestServiceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.TestServiceCompleted(this, new TestServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestServiceRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string TestServiceRest(string requestId, string data) {
        object[] results = this.Invoke("TestServiceRest", new object[] {
                    requestId,
                    data});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTestServiceRest(string requestId, string data, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("TestServiceRest", new object[] {
                    requestId,
                    data}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndTestServiceRest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void TestServiceRestAsync(string requestId, string data) {
        this.TestServiceRestAsync(requestId, data, null);
    }
    
    /// <remarks/>
    public void TestServiceRestAsync(string requestId, string data, object userState) {
        if ((this.TestServiceRestOperationCompleted == null)) {
            this.TestServiceRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestServiceRestOperationCompleted);
        }
        this.InvokeAsync("TestServiceRest", new object[] {
                    requestId,
                    data}, this.TestServiceRestOperationCompleted, userState);
    }
    
    private void OnTestServiceRestOperationCompleted(object arg) {
        if ((this.TestServiceRestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.TestServiceRestCompleted(this, new TestServiceRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LookupLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public LocationLookupResponse LookupLocation(LocationLookupRequest request) {
        object[] results = this.Invoke("LookupLocation", new object[] {
                    request});
        return ((LocationLookupResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLookupLocation(LocationLookupRequest request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LookupLocation", new object[] {
                    request}, callback, asyncState);
    }
    
    /// <remarks/>
    public LocationLookupResponse EndLookupLocation(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((LocationLookupResponse)(results[0]));
    }
    
    /// <remarks/>
    public void LookupLocationAsync(LocationLookupRequest request) {
        this.LookupLocationAsync(request, null);
    }
    
    /// <remarks/>
    public void LookupLocationAsync(LocationLookupRequest request, object userState) {
        if ((this.LookupLocationOperationCompleted == null)) {
            this.LookupLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupLocationOperationCompleted);
        }
        this.InvokeAsync("LookupLocation", new object[] {
                    request}, this.LookupLocationOperationCompleted, userState);
    }
    
    private void OnLookupLocationOperationCompleted(object arg) {
        if ((this.LookupLocationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LookupLocationCompleted(this, new LookupLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LookupLocationRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string LookupLocationRest(string requestId, string zipCode) {
        object[] results = this.Invoke("LookupLocationRest", new object[] {
                    requestId,
                    zipCode});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLookupLocationRest(string requestId, string zipCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LookupLocationRest", new object[] {
                    requestId,
                    zipCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndLookupLocationRest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void LookupLocationRestAsync(string requestId, string zipCode) {
        this.LookupLocationRestAsync(requestId, zipCode, null);
    }
    
    /// <remarks/>
    public void LookupLocationRestAsync(string requestId, string zipCode, object userState) {
        if ((this.LookupLocationRestOperationCompleted == null)) {
            this.LookupLocationRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupLocationRestOperationCompleted);
        }
        this.InvokeAsync("LookupLocationRest", new object[] {
                    requestId,
                    zipCode}, this.LookupLocationRestOperationCompleted, userState);
    }
    
    private void OnLookupLocationRestOperationCompleted(object arg) {
        if ((this.LookupLocationRestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LookupLocationRestCompleted(this, new LookupLocationRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ServiceTestRequest : ServiceRequestBase {
    
    private string dataField;
    
    /// <remarks/>
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationLookupRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceTestRequest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public abstract partial class ServiceRequestBase {
    
    private string requestIdField;
    
    /// <remarks/>
    public string RequestId {
        get {
            return this.requestIdField;
        }
        set {
            this.requestIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Location {
    
    private string stateField;
    
    private string countyField;
    
    private string cityField;
    
    private string zipCodeField;
    
    private string infoField;
    
    /// <remarks/>
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string County {
        get {
            return this.countyField;
        }
        set {
            this.countyField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationLookupResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceTestResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public abstract partial class ServiceResponseBase {
    
    private string requestIdField;
    
    private string[] errorsField;
    
    /// <remarks/>
    public string RequestId {
        get {
            return this.requestIdField;
        }
        set {
            this.requestIdField = value;
        }
    }
    
    /// <remarks/>
    public string[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class LocationLookupResponse : ServiceResponseBase {
    
    private Location[] dataField;
    
    /// <remarks/>
    public Location[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ServiceTestResponse : ServiceResponseBase {
    
    private string dataField;
    
    /// <remarks/>
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class LocationLookupRequest : ServiceRequestBase {
    
    private string zipCodeField;
    
    /// <remarks/>
    public string ZipCode {
        get {
            return this.zipCodeField;
        }
        set {
            this.zipCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void TestServiceCompletedEventHandler(object sender, TestServiceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TestServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal TestServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ServiceTestResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ServiceTestResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void TestServiceRestCompletedEventHandler(object sender, TestServiceRestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TestServiceRestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal TestServiceRestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void LookupLocationCompletedEventHandler(object sender, LookupLocationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LookupLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LookupLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public LocationLookupResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((LocationLookupResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void LookupLocationRestCompletedEventHandler(object sender, LookupLocationRestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LookupLocationRestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LookupLocationRestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
