<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="Ping">
        <s:complexType />
      </s:element>
      <s:element name="PingResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="PingResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="TestService">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:ServiceTestRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ServiceTestRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:ServiceRequestBase">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Data" type="s:string" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ServiceRequestBase" abstract="true">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="RequestId" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="TestServiceResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="TestServiceResult" type="tns:ServiceTestResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ServiceTestResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:ServiceResponseBase">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Data" type="s:string" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ServiceResponseBase" abstract="true">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="RequestId" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Errors" type="tns:ArrayOfString" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfString">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="LookupLocation">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="request" type="tns:LocationLookupRequest" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="LocationLookupRequest">
        <s:complexContent mixed="false">
          <s:extension base="tns:ServiceRequestBase">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="ZipCode" type="s:string" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:element name="LookupLocationResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="LookupLocationResult" type="tns:LocationLookupResponse" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="LocationLookupResponse">
        <s:complexContent mixed="false">
          <s:extension base="tns:ServiceResponseBase">
            <s:sequence>
              <s:element minOccurs="0" maxOccurs="1" name="Data" type="tns:ArrayOfLocation" />
            </s:sequence>
          </s:extension>
        </s:complexContent>
      </s:complexType>
      <s:complexType name="ArrayOfLocation">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="Location" nillable="true" type="tns:Location" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="Location">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="State" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="County" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="City" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="ZipCode" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="Info" type="s:string" />
        </s:sequence>
      </s:complexType>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="PingSoapIn">
    <wsdl:part name="parameters" element="tns:Ping" />
  </wsdl:message>
  <wsdl:message name="PingSoapOut">
    <wsdl:part name="parameters" element="tns:PingResponse" />
  </wsdl:message>
  <wsdl:message name="TestServiceSoapIn">
    <wsdl:part name="parameters" element="tns:TestService" />
  </wsdl:message>
  <wsdl:message name="TestServiceSoapOut">
    <wsdl:part name="parameters" element="tns:TestServiceResponse" />
  </wsdl:message>
  <wsdl:message name="LookupLocationSoapIn">
    <wsdl:part name="parameters" element="tns:LookupLocation" />
  </wsdl:message>
  <wsdl:message name="LookupLocationSoapOut">
    <wsdl:part name="parameters" element="tns:LookupLocationResponse" />
  </wsdl:message>
  <wsdl:portType name="ExampleWebServiceSoap">
    <wsdl:operation name="Ping">
      <wsdl:input message="tns:PingSoapIn" />
      <wsdl:output message="tns:PingSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="TestService">
      <wsdl:input message="tns:TestServiceSoapIn" />
      <wsdl:output message="tns:TestServiceSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="LookupLocation">
      <wsdl:input message="tns:LookupLocationSoapIn" />
      <wsdl:output message="tns:LookupLocationSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ExampleWebServiceSoap" type="tns:ExampleWebServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Ping">
      <soap:operation soapAction="http://tempuri.org/Ping" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TestService">
      <soap:operation soapAction="http://tempuri.org/TestService" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="LookupLocation">
      <soap:operation soapAction="http://tempuri.org/LookupLocation" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ExampleWebServiceSoap12" type="tns:ExampleWebServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Ping">
      <soap12:operation soapAction="http://tempuri.org/Ping" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TestService">
      <soap12:operation soapAction="http://tempuri.org/TestService" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="LookupLocation">
      <soap12:operation soapAction="http://tempuri.org/LookupLocation" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ExampleWebService">
    <wsdl:port name="ExampleWebServiceSoap" binding="tns:ExampleWebServiceSoap">
      <soap:address location="https://localhost:44355/ExampleWebService.asmx" />
    </wsdl:port>
    <wsdl:port name="ExampleWebServiceSoap12" binding="tns:ExampleWebServiceSoap12">
      <soap12:address location="https://localhost:44355/ExampleWebService.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
