<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SimpleApp</RootNamespace>
    <AssemblyName>CSharp.Ch07.TextbookCode.SimpleApp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.Ch07.TextbookCode.Utils\CSharp.Ch07.TextbookCode.Utils.csproj" />
  </ItemGroup>

</Project>
