<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch11.Supplemental._04.PerformanceCountersAndProfiling</RootNamespace>
    <AssemblyName>CSharp.Ch11.Supplemental.04.PerformanceCountersAndProfiling</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
