<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>WPFAsyncApp</RootNamespace>
    <AssemblyName>CSharp.Ch07.TextbookCode.WPFAsyncApp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.Ch07.TextbookCode.Utils\CSharp.Ch07.TextbookCode.Utils.csproj" />
  </ItemGroup>

</Project>
