//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     SYNTAX:  svcutil.exe /l:cs "<path to wsdl file>" /o:"<output CS class file path>"
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.WcfService.Models.Objects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestBase", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Samples.WcfService.Models.Objects.LocationLookupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Samples.WcfService.Models.Objects.ServiceTestRequest))]
    public partial class ServiceRequestBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RequestIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationLookupRequest", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    public partial class LocationLookupRequest : Samples.WcfService.Models.Objects.ServiceRequestBase
    {
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceTestRequest", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    public partial class ServiceTestRequest : Samples.WcfService.Models.Objects.ServiceRequestBase
    {
        
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Samples.WcfService.Models.Objects.LocationLookupResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Samples.WcfService.Models.Objects.ServiceTestResponse))]
    public partial class ServiceResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ErrorsField;
        
        private string RequestIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationLookupResponse", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    public partial class LocationLookupResponse : Samples.WcfService.Models.Objects.ServiceResponseBase
    {
        
        private Samples.WcfService.Models.Objects.Location[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Samples.WcfService.Models.Objects.Location[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceTestResponse", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    public partial class ServiceTestResponse : Samples.WcfService.Models.Objects.ServiceResponseBase
    {
        
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Samples.WcfService.Models.Objects")]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityField;
        
        private string CountyField;
        
        private string InfoField;
        
        private string StateField;
        
        private string ZipCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IExampleWebService")]
public interface IExampleWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/Ping", ReplyAction="http://tempuri.org/IExampleWebService/PingResponse")]
    string Ping();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/Ping", ReplyAction="http://tempuri.org/IExampleWebService/PingResponse")]
    System.Threading.Tasks.Task<string> PingAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/TestService", ReplyAction="http://tempuri.org/IExampleWebService/TestServiceResponse")]
    Samples.WcfService.Models.Objects.ServiceTestResponse TestService(Samples.WcfService.Models.Objects.ServiceTestRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/TestService", ReplyAction="http://tempuri.org/IExampleWebService/TestServiceResponse")]
    System.Threading.Tasks.Task<Samples.WcfService.Models.Objects.ServiceTestResponse> TestServiceAsync(Samples.WcfService.Models.Objects.ServiceTestRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/TestServiceRest", ReplyAction="http://tempuri.org/IExampleWebService/TestServiceRestResponse")]
    string TestServiceRest(string requestId, string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/TestServiceRest", ReplyAction="http://tempuri.org/IExampleWebService/TestServiceRestResponse")]
    System.Threading.Tasks.Task<string> TestServiceRestAsync(string requestId, string data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/LookupLocation", ReplyAction="http://tempuri.org/IExampleWebService/LookupLocationResponse")]
    Samples.WcfService.Models.Objects.LocationLookupResponse LookupLocation(Samples.WcfService.Models.Objects.LocationLookupRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/LookupLocation", ReplyAction="http://tempuri.org/IExampleWebService/LookupLocationResponse")]
    System.Threading.Tasks.Task<Samples.WcfService.Models.Objects.LocationLookupResponse> LookupLocationAsync(Samples.WcfService.Models.Objects.LocationLookupRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/LookupLocationRest", ReplyAction="http://tempuri.org/IExampleWebService/LookupLocationRestResponse")]
    string LookupLocationRest(string requestId, string zipCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExampleWebService/LookupLocationRest", ReplyAction="http://tempuri.org/IExampleWebService/LookupLocationRestResponse")]
    System.Threading.Tasks.Task<string> LookupLocationRestAsync(string requestId, string zipCode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IExampleWebServiceChannel : IExampleWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ExampleWebServiceClient : System.ServiceModel.ClientBase<IExampleWebService>, IExampleWebService
{
    
    public ExampleWebServiceClient()
    {
    }
    
    public ExampleWebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ExampleWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ExampleWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ExampleWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Ping()
    {
        return base.Channel.Ping();
    }
    
    public System.Threading.Tasks.Task<string> PingAsync()
    {
        return base.Channel.PingAsync();
    }
    
    public Samples.WcfService.Models.Objects.ServiceTestResponse TestService(Samples.WcfService.Models.Objects.ServiceTestRequest request)
    {
        return base.Channel.TestService(request);
    }
    
    public System.Threading.Tasks.Task<Samples.WcfService.Models.Objects.ServiceTestResponse> TestServiceAsync(Samples.WcfService.Models.Objects.ServiceTestRequest request)
    {
        return base.Channel.TestServiceAsync(request);
    }
    
    public string TestServiceRest(string requestId, string data)
    {
        return base.Channel.TestServiceRest(requestId, data);
    }
    
    public System.Threading.Tasks.Task<string> TestServiceRestAsync(string requestId, string data)
    {
        return base.Channel.TestServiceRestAsync(requestId, data);
    }
    
    public Samples.WcfService.Models.Objects.LocationLookupResponse LookupLocation(Samples.WcfService.Models.Objects.LocationLookupRequest request)
    {
        return base.Channel.LookupLocation(request);
    }
    
    public System.Threading.Tasks.Task<Samples.WcfService.Models.Objects.LocationLookupResponse> LookupLocationAsync(Samples.WcfService.Models.Objects.LocationLookupRequest request)
    {
        return base.Channel.LookupLocationAsync(request);
    }
    
    public string LookupLocationRest(string requestId, string zipCode)
    {
        return base.Channel.LookupLocationRest(requestId, zipCode);
    }
    
    public System.Threading.Tasks.Task<string> LookupLocationRestAsync(string requestId, string zipCode)
    {
        return base.Channel.LookupLocationRestAsync(requestId, zipCode);
    }
}
