//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.WebForms
{
    public partial class Default
    {
        /// <summary>
        /// txtZipCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZipCode;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// pnlResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResults;

        /// <summary>
        /// litZipCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litZipCode;

        /// <summary>
        /// gridResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gridResults;
    }
}
