<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Supplemental.Algorithms.BigOConcepts</RootNamespace>
    <AssemblyName>CSharp.Supplemental.Algorithms.BigOConcepts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.Supplemental.Algorithms.Shared\CSharp.Supplemental.Algorithms.Shared.csproj" />
  </ItemGroup>

</Project>
