<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Samples.MvcWebApi.Core.Common</RootNamespace>
    <AssemblyName>Samples.MvcWebApi.Core.Common</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" />
    <None Include="LectureNotes.md" />
  </ItemGroup>

</Project>
