<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>CSharp.Ch04.TextbookCode.ShortPathNames</RootNamespace>
    <AssemblyName>CSharp.Ch04.TextbookCode.ShortPathNames</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

</Project>
