<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApplication2</RootNamespace>
    <AssemblyName>CSharp.Ch09.TextbookCode.Serialization</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

</Project>
