<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>NorthwindsConsole</RootNamespace>
    <AssemblyName>CSharp.Ch09.TextbookCode.NorthwindsConsole</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SQL Scripts\" />
  </ItemGroup>

</Project>
