<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CSharp.Ch06.Supplemental.s05.ExceptionHandling</RootNamespace>
    <AssemblyName>CSharp.Ch06.Supplemental.05.ExceptionHandling</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSharp.SharedLibrary\CSharp.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
